name: SetupUbuntuRunner
inputs:
  workflow_ref:
    description: 'Reference to this workflow: owner/repo@branch'
    type: string
    required: true

outputs:
  actions_repo:
    value: ${{ steps.checkout_repo.outputs.actions_repo }}
  actions_repo_owner:
    value: ${{ steps.checkout_repo.outputs.actions_repo_owner }}
  actions_repo_dir:
    value: ${{ steps.checkout_repo.outputs.actions_repo_dir }}
  actions_branch:
    value: ${{ steps.checkout_repo.outputs.actions_branch }}

runs:
  using: "composite"
  steps:
    - name: "Checkout actions repo"
      id: checkout_repo
      shell: bash
      run: |
        # Checkout actions repo
        ref="${{ inputs.workflow_ref }}"
        repo=${ref%%@*}
        repo_owner=${repo%%/*}
        repo_dir=${repo##*/}
        branch=${ref##*@}
        echo "*** Cloning ${repo} branch ${branch}"
        git clone ${GITHUB_SERVER_URL}/${repo}
        git -C ${repo_dir} checkout ${branch}
        echo "actions_repo=$repo" >> "$GITHUB_OUTPUT"
        echo "actions_repo_owner=$repo_owner" >> "$GITHUB_OUTPUT"
        echo "actions_repo_dir=$repo_dir" >> "$GITHUB_OUTPUT"
        echo "actions_branch=$branch" >> "$GITHUB_OUTPUT"

    - name: "Set sysctls"
      shell: bash
      run: |
        # Set sysctls and add asteriskci user
        echo "************* Current User Info ***************"
        whoami
        id
        echo "***************************************"
        
        sudo sysctl -w kernel.core_pattern=/tmp/core-%e-%t
        sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0 || :
        sudo chmod 1777 /tmp
        sudo groupadd -g 2000 asteriskci
        sudo useradd -u 2000 -g 2000 asteriskci

    - name: "Install Packages"
      shell: bash
      run: |
        # Install packages
        echo "Installing github cli repo"
        wget -q -O/tmp/githubcli-archive-keyring.gpg https://cli.github.com/packages/githubcli-archive-keyring.gpg
        sudo install --mode=0644 -D -t /etc/apt/keyrings /tmp/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" > /tmp/github-cli.list
        sudo install --mode=0644 -D -t /etc/apt/sources.list.d /tmp/github-cli.list
        echo "Installing dev packages"
        sudo apt-get update -qq >/dev/null
        sudo apt-get install -qq binutils-dev freetds-dev \
          libasound2-dev libbluetooth-dev libc-client2007e-dev \
          libcap-dev libcfg-dev libcodec2-dev libcorosync-common-dev \
          libcpg-dev libcurl4-openssl-dev libedit-dev libfftw3-dev \
          libgmime-3.0-dev libgsm1-dev libical-dev libiksemel-dev \
          libjansson-dev libldap-dev libldap2-dev \
          liblua5.2-dev libneon27-dev libnewt-dev libogg-dev libpopt-dev \
          libradcli-dev libresample1-dev libsndfile1-dev libsnmp-dev \
          libspandsp-dev libspeex-dev libspeexdsp-dev libsrtp2-dev \
          libunbound-dev liburiparser-dev libvorbis-dev libxslt1-dev \
          xmlstarlet python3-pystache >/dev/null
        echo "Installing addons"
        sudo apt-get install -qq cmake libsctp-dev sudo python3-dev python3*-venv \
          postgresql git libpcap-dev nano python3-pip alembic odbc-postgresql \
          unixodbc unixodbc-dev python3-psycopg2 rsync gh jq >/dev/null
