name: DumpContext
inputs:
  action-inputs:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: "Dump github context"
      shell: bash
      run: |
        set -e +v +x
        echo "::group::inputs"
        echo '${{inputs.action-inputs}}'
        echo "::endgroup::"
        
        echo "::group::ctxenv"
        echo '${{toJSON(env)}}'
        echo "::endgroup::"
        
        echo "::group::env"
        printenv | sort
        echo "::endgroup::"
        
        echo "::group::github_context"
        echo '${{toJSON(github)}}'
        echo "::endgroup::"
        exit 0
