name: DumpContext
inputs:
  action-inputs:
    required: false
    type: string
    default: '{}'
  action-vars:
    required: false
    type: string
    default: '{}'

runs:
  using: "composite"
  steps:
    - name: "Dump github context"
      shell: bash
      run: |
        set +e +v +x
        echo "::group::inputs"
        cat <<%%EOF%%
        ${{toJSON(fromJSON(inputs.action-inputs))}}
        %%EOF%%
        echo "::endgroup::"
        
        echo "::group::vars"
        cat <<%%EOF%%
        ${{toJSON(fromJSON(inputs.action-vars))}}
        %%EOF%%
        echo "::endgroup::"
        
        echo "::group::ctxenv"
        cat <<%%EOF%%
        ${{toJSON(env)}}
        %%EOF%%
        echo "::endgroup::"
        
        echo "::group::env"
        printenv | sort
        echo "::endgroup::"
        
        echo "::group::github_context"
        cat <<%%EOF%%
        ${{toJSON(github)}}
        %%EOF%%
        echo "::endgroup::"

        echo "::group::GITHUB_WORKSPCE: ${GITHUB_WORKSPACE}"
        ls -al ${GITHUB_WORKSPACE}
        echo "::endgroup::"

        echo "::group::HOME: ${HOME}"
        ls -al ${HOME}
        echo "::endgroup::"

        echo "::group::RUNNER_WORKSPACE: ${RUNNER_WORKSPACE}"
        ls -al ${RUNNER_WORKSPACE}
        echo "::endgroup::"

        if [ -n "${GITHUB_ACTION_PATH}" ] ; then
          echo "::group::GITHUB_ACTION_PATH: ${GITHUB_ACTION_PATH}"
          ls -al ${GITHUB_ACTION_PATH}
          echo "::endgroup::"
        fi



        exit 0
