name: RunAsteriskUnitTests
inputs:
  asterisk-repo:
    required: true
    type: string
    default: ${{github.repository}}
  pr-number:
    required: true
    type: number
    default: 0
  pr-commit:
    required: false
    type: string
  base-branch:
    required: true
    type: string
  cache-dir:
    required: false
    type: string
    default: cache
  github-token:
    description: 'GitHub API Access Token.'
    default: ${{ github.token }}
    required: false
  unittest-command:
    description: 'Asterisk CLI command to run unit tests.'
    default: "test execute all"
    required: false

runs:
  using: "composite"
  steps:

    - name: SetupEnv
      id: setup-env
      shell: bash
      run: |
        echo "${{env.GITHUB_ACTION}} SetupEnv"
        CACHE_DIR=$(realpath -m ${{inputs.cache-dir}})
        cat <<EOF >> "$GITHUB_ENV"
        RAUT_OUTPUT_DIR=${CACHE_DIR}/output
        RAUT_BRANCH=${{inputs.base-branch}}
        RAUT_SCRIPT_DIR=$(realpath ${GITHUB_ACTION_PATH}/../scripts)
        EOF
      
    - name: Run Unit Tests
      id: run-unit-tests
      shell: bash
      if: ${{ success() }}
      run: |
        echo "${{env.GITHUB_ACTION}} Running unit test command ${{inputs.unittest-command}}"
        ${RAUT_SCRIPT_DIR}/runUnittests.sh --no-expect --github \
          --user-group=asteriskci:users \
          --output-dir=${RAUT_OUTPUT_DIR} \
          --output-xml=${RAUT_OUTPUT_DIR}/unittests-results.xml \
          --unittest-command="${{inputs.unittest-command}}"

    - name: Save Output
      id: save-output
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: Unit Test Output
        path: ${{env.RAUT_OUTPUT_DIR}}

    - name: Publish Unit Test Results
      id: publish-results
      if: always() && inputs.pr-number > 0
      uses: dorny/test-reporter@v1
      with:
        name: Testsuite Test Results
        path: ${{ env.RAUT_OUTPUT_DIR }}/*.xml
        reporter: java-junit
        list-suites: all
        list-tests: failed
        max-annotations: 0
        fail-on-error: true
        token: ${{inputs.github-token}}


#    - name: Publish Unit Test Results
#      if: always() && inputs.pr-number > 0
#      uses: EnricoMi/publish-unit-test-result-action/composite@v2.4.2
#      with:
#        check_name: Unit Test Results
#        files: ${{env.RAUT_OUTPUT_DIR}}/*.xml
#        comment_mode: always
#        action_fail: true
#      env:
#        GITHUB_REPOSITORY: ${{ inputs.asterisk-repo }}
