name: RunAsteriskUnitTests
inputs:
  asterisk_repo:
    required: true
    type: string
    default: ${{github.repository}}
  pr_number:
    required: true
    type: number
    default: 0
  pr_commit:
    required: false
    type: string
  base_branch:
    required: true
    type: string
  cache_dir:
    required: false
    type: string
    default: cache
  github_token:
    description: 'GitHub API Access Token.'
    default: ${{ github.token }}
    required: false
  unittest_command:
    description: 'Asterisk CLI command to run unit tests.'
    default: "test execute all"
    required: false

runs:
  using: "docker"
  image: "docker://ghcr.io/asterisk/asteriskci-agent-rocky8:latest"
  args:
    - entrypointRunAsteriskUnitTests.sh
