name: GetCherryPickBranchesFromPR
inputs:
  repo:
    required: true
    type: string
  pr_number:
    required: true
    type: number
  cherry_pick_regex:
    required: true
    type: string
  include_branches:
    required: false
    type: string
  github_token:
    description: 'GitHub API Access Token.'
    default: ${{ github.token }}
    required: false

outputs:
  branch_count:
    description: "Number of branches"
    value: ${{ steps.getbranches.outputs.branch_count }}
  branches:
    description: "List of branches formatted as a JSON array"
    value: ${{ steps.getbranches.outputs.branches }}
  forced_none:
    description: "PR had 'cherry-pick-to: none'"
    value: ${{ steps.getbranches.outputs.forced_none }}

runs:
  using: "composite"
  steps:
    - name: Get cherry-pick branches
      id: getbranches
      shell: bash
      env:
        GITHUB_TOKEN:      ${{inputs.github_token}}
        GH_TOKEN:          ${{inputs.github_token}}
        INCLUDE_BRANCHES:    ${{inputs.include_branches}}
      run: |
        echo "${{env.GITHUB_ACTION}} Get branches"
        branchlist=$(gh api /repos/${{inputs.repo}}/issues/${{inputs.pr_number}}/comments \
          --jq '.[].body | match("${{inputs.cherry_pick_regex}}"; "g") | .captures[0].string' | tr '\n' ' ')
        echo $branchlist ${INCLUDE_BRANCHES//,/ }
        if [[ "$branchlist" =~ none ]] ; then
          echo "forced_none=true" >> "$GITHUB_OUTPUT"
        else
          echo "forced_none=false" >> "$GITHUB_OUTPUT"
        fi
        eval declare -a BRANCHES=( ${branchlist/none/} ${INCLUDE_BRANCHES//,/ } )
        declare -p BRANCHES
        declare -i branch_count=0
        json='['
        for branch in ${BRANCHES[@]} ; do
          echo "Will cherry-pick to branch $branch"
          [ $branch_count -ne 0 ] && json+=','
          json+="\"$branch\""
          branch_count+=1
        done
        json+=']'
        echo "branches=$json" >> "$GITHUB_OUTPUT"
        echo "branch_count=$branch_count" >> "$GITHUB_OUTPUT"
        if [ $branch_count -eq 0 ] ; then
          echo "No branches needing cherry picks identified"
        else
          echo "Branches identified for cherry-picks: $json"
        fi
