name: TestCompositeAction
inputs:
  test_type:
    required: true
    type: string
outputs:
  result:
    value: ${{steps.teststep.output.result}}
runs:
  using: "composite"
  steps:
    - name: TestStep
      timeout-minutes: 1
      id: teststep
      shell: bash
      run: |
        echo "Exiting with RC 0 (forced)"
        echo "result=success" >> $GITHUB_OUTPUT
        exit 0

    - name: TestDockerAction
      uses: ./TestDockerAction
      with:
        test_type: basic
