name: GetTestsuitePRFromAsteriskPR
inputs:
  repo:
    required: true
    type: string
  pr_number:
    required: true
    type: number
  testsuite_test_pr_regex:
    required: true
    type: string
  testsuite_test_auto_merge_regex:
    required: true
    type: string
  github_token:
    description: 'GitHub API Access Token.'
    default: ${{ github.token }}
    required: false

outputs:
  testsuite_test_pr:
    description: "Testsuite test PR"
    value: ${{ steps.getpr.outputs.testsuite_test_pr }}
  testsuite_test_auto_merge:
    description: "Auto merge testsuite PR?"
    value: ${{ steps.getpr.outputs.testsuite_test_auto_merge }}

runs:
  using: "composite"
  steps:
    - name: Get testsuite pr
      id: getpr
      shell: bash
      env:
        GITHUB_TOKEN:      ${{inputs.github_token}}
        GH_TOKEN:          ${{inputs.github_token}}
      run: |
        echo "${{env.GITHUB_ACTION}} Get Testsuite PR number"
        testsuite_pr=$(gh api /repos/${{inputs.repo}}/issues/${{inputs.pr_number}}/comments \
          --jq '.[].body | match("${{inputs.testsuite_test_pr_regex}}"; "g") | .captures[0].string') || \
          { echo "::error::Unable to retrieve comments for /repos/${{inputs.repo}}/issues/${{inputs.pr_number}}" ; exit 1 ; }
        if [ -n "${testsuite_pr}" ] ; then
          echo "Testsuite PR: ${testsuite_pr}"
          echo "testsuite_test_pr=${testsuite_pr}" >> "$GITHUB_OUTPUT"
        else
          echo "Testsuite PR not found"
        fi
        
        echo "${{env.GITHUB_ACTION}} Get Testsuite Auto Merge"
        testsuite_automerge=$(gh api /repos/${{inputs.repo}}/issues/${{inputs.pr_number}}/comments \
          --jq '.[].body | match("${{inputs.testsuite_test_auto_merge_regex}}"; "g") | .captures[0].string') || \
          { echo "::error::Unable to retrieve comments for /repos/${{inputs.repo}}/issues/${{inputs.pr_number}}" ; exit 1 ; }
        if [ -n "${testsuite_automerge}" ] ; then
          echo "Testsuite automerge: ${testsuite_automerge}"
          echo "testsuite_test_auto_merge=${testsuite_automerge}" >> "$GITHUB_OUTPUT"
        else
          echo "Testsuite automerge not identified"
        fi

