name: AsteriskRecheckPR
run-name: "${{github.workflow}}-${{github.event.label.name}}-${{github.event.number}}"
on:
  workflow_call:
    secrets:
      ASTERISKTEAM_PAT:
        required: true

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: SetupUbuntuRunner
        uses: asterisk/asterisk-ci-actions/SetupUbuntuRunner@main
      - name: Set Label
        id: setlabel
        env:
          GH_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{github.event.number}}
        run: | 
          gh pr edit --repo ${{github.repository}} \
            --remove-label ${{vars.RECHECKPR_LABEL}} \
            --remove-label ${{vars.PR_SUBMIT_TESTS_PASSED}} \
            --remove-label  ${{vars.PR_SUBMIT_TESTS_FAILED}} \
            --add-label ${{vars.PR_SUBMIT_TESTING_IN_PROGRESS}} \
            $PR_NUMBER || :

  RunAsteriskUnitTests:
    uses: ./.github/workflows/RunAsteriskUnitTests.yml
    with:
      asterisk_repo:     ${{github.repository}}
      pr_number:         ${{github.event.number}}
      base_branch:       ${{github.event.pull_request.base.ref}}
      build_options:     ${{vars.BUILD_OPTIONS}}
      unittest_command:  ${{vars.UNITTEST_COMMAND}}

  RunAsteriskGateTests:
    strategy:
      fail-fast: false
      matrix:
        group: ${{ fromJSON(vars.GATETEST_LIST) }}
    uses: ./.github/workflows/RunAsteriskGateTests.yml
    with:
      test_type:         Gate
      asterisk_repo:     ${{github.repository}}
      pr_number:         ${{github.event.number}}
      base_branch:       ${{github.event.pull_request.base.ref}}
      testsuite_repo:    ${{vars.TESTSUITE_REPO}}
      gatetest_group:    ${{matrix.group}}
      gatetest_command:  ${{ toJSON(fromJSON(vars.GATETEST_COMMANDS)[matrix.group]) }}

  TestResults:
    if: always()
    runs-on: ubuntu-latest
    needs: [RunAsteriskUnitTests,RunAsteriskGateTests]
    steps:
      - name: Check test matrix status
        env:
          GH_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          RESULT_UNIT: ${{ needs.RunAsteriskUnitTests.result }}
          RESULT_GATE: ${{ needs.RunAsteriskGateTests.result }}
          TESTS_PASSED: ${{ vars.PR_SUBMIT_TESTS_PASSED }}
          TESTS_FAILED: ${{ vars.PR_SUBMIT_TESTS_FAILED }}
        run: |
          declare -i rc=0
          echo "all results: ${{ toJSON(needs.*.result) }}"
          case $RESULT_UNIT in
            success)
              echo "::notice::Unit tests passed"
              ;;
            skipped)
              echo "::error::Unit tests were skipped because of an earlier failure"
              rc+=1
              ;;
            *)
              echo "::error::One or more unit tests failed ($RESULT_UNIT)"
              rc+=1
          esac
          case $RESULT_GATE in
            success)
              echo "::notice::Gate tests passed"
              ;;
            skipped)
              echo "::error::Gate tests were skipped because of an earlier failure"
              rc+=1
              ;;
            *)
              echo "::error::One or more gate tests failed ($RESULT_GATE)"
              rc+=1
          esac
          
          label=$TESTS_PASSED
          if [ $rc != 0 ] ; then
            label=$TESTS_FAILED
          fi
          gh pr edit --repo ${{github.repository}} \
            --remove-label ${{vars.PR_SUBMIT_TESTING_IN_PROGRESS}} \
            --add-label $label \
              $PR_NUMBER || :
          exit $rc
