name: PRStateChangedPriv
on:
  workflow_call:
    inputs:
      actions_ref:
        description: 'JSON object reference to the actions: { "owner": "asterisk", "repo": "asterisk-ci-actions", "branch": "main" }'
        type: string
        required: false
        default: '{ "owner": "asterisk", "repo": "asterisk-ci-actions", "branch": "main" }'
    secrets:
      TOKEN:
        required: true

env:
  ACTION:     ${{ github.event.action }}
  RESULT:     ${{ github.event.workflow_run.conclusion }}
  REPO:       ${{ github.repository }}
  GH_TOKEN:   ${{ secrets.TOKEN }}
  SHA:        ${{ github.event.workflow_run.head_sha }}
  HEAD_REPO:  ${{ github.event.workflow_run.head_repository.full_name }}
  WORKFLOW_NAME:   ${{ github.event.workflow.name }}
  WORKFLOW_RUN:    ${{ github.event.workflow_run.name }}
  WORKFLOW_RUN_ID: ${{ github.event.workflow_run.id }}
  BUILD_CACHE_KEY_PREFIX: ${{ github.event.workflow.name }}-${{ github.event.workflow_run.run_number }}
  ACTIONS_OWNER:    ${{ fromJSON(inputs.actions_ref).owner }}
  ACTIONS_REPO:     ${{ fromJSON(inputs.actions_ref).repo }}
  ACTIONS_BRANCH:   ${{ fromJSON(inputs.actions_ref).branch }}
  SCRIPT_DIR:       ${{ github.workspace }}/asterisk-ci-actions/scripts
  TESTING_IN_PROGRESS: ${{ vars.PR_SUBMIT_TESTING_IN_PROGRESS }}
  TESTS_PASSED:        ${{ vars.PR_SUBMIT_TESTS_PASSED }}
  TESTS_FAILED:        ${{ vars.PR_SUBMIT_TESTS_FAILED }}

jobs:
  PRStateChangedPriv:
    if: ( !contains(fromJSON('["skipped", "cancelled"]'), github.event.workflow_run.conclusion) )
    runs-on: ubuntu-latest
    outputs:
      PR_NUMBER:     ${{ steps.getpr.outputs.PR_NUMBER }}
      BASE_BRANCH:   ${{ steps.getpr.outputs.BASE_BRANCH }}

    steps:
      - name: Setup Runner
        run: |
          # Setup
          wget -qO asterisk-ci-actions.tar.gz \
            https://github.com/${ACTIONS_OWNER}/${ACTIONS_REPO}/archive/refs/heads/${ACTIONS_BRANCH}.tar.gz
          tar -xf asterisk-ci-actions.tar.gz --transform="s/^${ACTIONS_REPO}-${ACTIONS_BRANCH}/asterisk-ci-actions/g"

      - name: DumpEnvironment
        uses: asterisk/asterisk-ci-actions/DumpEnvironmentAction@main

      - name: Get PR Number
        id: getpr
        run: |
          # Getting PR number from workflow_run.name
          # PR_NUMBER and BASE_BRANCH will be set by the script
          output=$(${SCRIPT_DIR}/getPRFromTriggeringWorkflow.sh \
            --repo=${REPO} \
            --workflow-run="${WORKFLOW_RUN}" \
            --workflow-run-id=${WORKFLOW_RUN_ID})
          BASE_BRANCH=$(echo $output | jq -r '.base_branch')
          PR_NUMBER=$(echo $output | jq -r '.pr_number')
          BUILD_CACHE_KEY=${BUILD_CACHE_KEY_PREFIX}-${PR_NUMBER}-${BASE_BRANCH}
          echo "BUILD_CACHE_KEY=${BUILD_CACHE_KEY}" >> ${GITHUB_ENV}

      - name: OnRequested
        if: github.event.action == 'requested'
        run: |
          # OnRequested
          gh cache delete -R ${REPO} ${BUILD_CACHE_KEY} &> /dev/null || :
          #
          gh pr edit --repo ${REPO} \
            --remove-label ${TESTS_PASSED} \
            --remove-label ${TESTS_FAILED} \
            --add-label ${TESTING_IN_PROGRESS} \
            $PR_NUMBER || :

      - name: OnCompleted
        if: ( github.event.action == 'completed' )
        env:
          CHERRY_PICK_REGEX:       ${{ vars.CHERRY_PICK_REGEX }}
          CHERRY_PICK_REMINDER:    ${{ vars.CHERRY_PICK_REMINDER }}
          SQUASH_COMMITS_REMINDER: ${{ vars.SQUASH_COMMITS_REMINDER }}
          USER_NOTE_REMINDER:      ${{ vars.USER_NOTE_REMINDER }}
          UPGRADE_NOTE_REMINDER:   ${{ vars.UPGRADE_NOTE_REMINDER }}
        run: |
          # OnCompleted ${{github.event.workflow_run.conclusion}}
          label=""
          case $RESULT in
            success)
              label=$TESTS_PASSED
              gh cache delete -R ${REPO} ${BUILD_CACHE_KEY} || :
              ;;
            failure)
              label=$TESTS_FAILED
              ;;
            cancelled)
              gh cache delete -R ${REPO} ${BUILD_CACHE_KEY} || :
              ;;
            skipped)
              ;;
            *)
              ;;
          esac
          gh pr edit --repo ${REPO} \
            --remove-label ${TESTING_IN_PROGRESS} \
            ${label:+--add-label $label} \
              $PR_NUMBER || :

          if [[ $RESULT =~ (success|failure) ]] ; then
            ${SCRIPT_DIR}/addCherryPickReminderIfNeeded.sh \
              --repo=${REPO} \
              --pr-number=${PR_NUMBER} \
              --cherry-pick-regex="${CHERRY_PICK_REGEX}" \
              --cherry-pick-reminder="${CHERRY_PICK_REMINDER}"

            ${SCRIPT_DIR}/createJobSummary.sh \
              --result=${RESULT} \
              --repo=${REPO} \
              --workflow-name="${WORKFLOW_NAME}" \
              --pr-number=${PR_NUMBER} \
              --workflow-run=${WORKFLOW_RUN_ID} \
              --tmp-dir=./run-${WORKFLOW_RUN_ID} \
              --job-summary-output=job_summary.txt \
              --add-pr-comment \
              --verbose || :
          fi
          exit 0
