name: RecheckPR
run-name: "${{ github.workflow }}-${{ github.event.label.name }}-${{ github.event.number }}"
on:
  workflow_call:
    inputs:
      actions_ref:
        description: 'JSON object reference to the actions: { "owner": "asterisk", "repo": "asterisk-ci-actions", "branch": "main" }'
        type: string
        required: false
        default: '{ "owner": "asterisk", "repo": "asterisk-ci-actions", "branch": "main" }'
    secrets:
      TOKEN:
        required: true

env:
  PR_NUMBER: ${{ github.event.number }}
  ACTIONS_OWNER:     ${{ fromJSON(inputs.actions_ref).owner }}
  ACTIONS_REPO:      ${{ fromJSON(inputs.actions_ref).repo }}
  ACTIONS_BRANCH:    ${{ fromJSON(inputs.actions_ref).branch }}
  SCRIPT_DIR:        ${{ github.workspace }}/asterisk-ci-actions/scripts

jobs:
  Setup:
    runs-on: ubuntu-latest
    outputs:
      testsuite_test_pr:  ${{ steps.prestart.outputs.TESTSUITE_TEST_PR }}
    steps:
      - name: Setup Runner
        run: |
          # Setup
          wget -qO asterisk-ci-actions.tar.gz \
            https://github.com/${ACTIONS_OWNER}/${ACTIONS_REPO}/archive/refs/heads/${ACTIONS_BRANCH}.tar.gz
          tar -xf asterisk-ci-actions.tar.gz --transform="s/^${ACTIONS_REPO}-${ACTIONS_BRANCH}/asterisk-ci-actions/g"

      - name: PreStart
        id: prestart
        env:
          REPO: ${{ github.repository }}
          RECHECKPR_LABEL:    ${{ vars.RECHECKPR_LABEL }}
          PR_SUBMIT_TESTS_PASSED: ${{ vars.PR_SUBMIT_TESTS_PASSED }}
          PR_SUBMIT_TESTS_FAILED: ${{ vars.PR_SUBMIT_TESTS_FAILED }}
          PR_SUBMIT_TESTING_IN_PROGRESS: ${{ vars.PR_SUBMIT_TESTING_IN_PROGRESS }}
          TESTSUITE_TEST_PR_REGEX: ${{ vars.TESTSUITE_TEST_PR_REGEX }}
          GH_TOKEN:  ${{ secrets.TOKEN }}
        run: | 
          gh pr edit --repo ${REPO} \
            --remove-label ${RECHECKPR_LABEL} \
            --remove-label ${PR_SUBMIT_TESTS_PASSED} \
            --remove-label ${PR_SUBMIT_TESTS_FAILED} \
            --add-label ${PR_SUBMIT_TESTING_IN_PROGRESS} \
            ${PR_NUMBER} || :

          # Testsuite PR will be placed in TESTSUITE_TEST_PR in both
          # GITHUB_ENV and GITHUB_OUTPUT by the script.
          ${SCRIPT_DIR}/getTestsuitePRfromAsteriskPR.sh \
            --repo=${REPO} \
            --pr-number=${PR_NUMBER} \
            --testsuite-pr-regex="${TESTSUITE_TEST_PR_REGEX}"

  Check:
    name: Check
    needs: Setup
    uses: ./.github/workflows/AsteriskUnitGateTest.yml
    with:
      test_type:         prrecheck
      asterisk_repo:     ${{ github.repository }}
      pr_number:         ${{ github.event.number }}
      base_branch:       ${{ github.event.pull_request.base.ref }}
      is_cherry_pick:    false
      build_options:     ${{ vars.BUILD_OPTIONS }}
      unittest_command:  ${{ vars.UNITTEST_COMMAND }}
      testsuite_repo:    ${{ vars.TESTSUITE_REPO }}
      testsuite_test_pr: ${{ needs.Setup.outputs.testsuite_test_pr }}
      gatetest_list:     ${{ vars.GATETEST_LIST }}
      gatetest_commands: ${{ vars.GATETEST_COMMANDS }}
    secrets: inherit

  TestResults:
    if: always()
    runs-on: ubuntu-latest
    needs: [Check]
    steps:
      - name: Check status
        env:
          REPO:              ${{ github.repository }}
          GH_TOKEN:          ${{ secrets.TOKEN }}
          RESULT:            ${{ needs.Check.result }}
          IN_PROGRESS_LABEL: ${{ vars.PR_SUBMIT_TESTING_IN_PROGRESS }}
          PASSED_LABEL:      ${{ vars.PR_SUBMIT_TESTS_PASSED }}
          FAILED_LABEL:      ${{ vars.PR_SUBMIT_TESTS_FAILED }}
        run: |
          declare -i rc=0
          case ${RESULT} in
            success)
              echo "All tests passed"
              ;;
            skipped)
              echo "One or more tests were skipped because of an earlier failure"
              rc+=1
              ;;
            *)
              echo "One or more tests failed ($RESULT)"
              rc+=1
          esac
          [ ${rc} -gt 0 ] && label=${FAILED_LABEL} || label=${PASSED_LABEL}
          gh pr edit --repo ${REPO} \
            --remove-label ${IN_PROGRESS_LABEL} \
            --add-label ${label} \
            ${PR_NUMBER} || :
          exit 0

