name: AsteriskCherryPickTest
on:
  workflow_call:
    secrets:
      TOKEN:
        required: true

env:
  PR_NUMBER: ${{ github.event.number }}
  VAR_CHERRY_PICK_TEST_LABEL: ${{vars.CHERRY_PICK_TEST_LABEL}}

jobs:
  IdentifyBranches:
    name: IdentifyBranches
    runs-on: ubuntu-latest
    outputs:
      branches:     ${{ steps.getbranches.outputs.branches }}
      branch_count: ${{ steps.getbranches.outputs.branch_count }}
    steps:
      - name: Remove Trigger Label, Add InProgress Label
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "VCPTL: $VAR_CHERRY_PICK_TEST_LABEL"
          gh pr edit --repo ${{github.repository}} \
            --remove-label ${{vars.CHERRY_PICK_TEST_LABEL}} \
            --remove-label ${{vars.CHERRY_PICK_CHECKS_PASSED_LABEL}} \
            --remove-label ${{vars.CHERRY_PICK_CHECKS_FAILED_LABEL}} \
            --remove-label ${{vars.CHERRY_PICK_GATES_PASSED_LABEL}} \
            --remove-label ${{vars.CHERRY_PICK_GATES_FAILED_LABEL}} \
            --remove-label ${{vars.CHERRY_PICK_TESTING_IN_PROGRESS}} \
            ${{env.PR_NUMBER}} || :

      - name: Get cherry-pick branches
        uses: asterisk/asterisk-ci-actions/GetCherryPickBranchesFromPR@main
        id: getbranches
        with:
          repo:                    ${{github.repository}}
          pr_number:               ${{env.PR_NUMBER}}
          cherry_pick_regex:       ${{vars.CHERRY_PICK_REGEX}}
          github_token:            ${{ secrets.TOKEN }}

      - name: Check Branch Count
        if: ${{ steps.getbranches.outputs.branch_count > 0 }}
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          gh pr edit --repo ${{github.repository}} \
          --add-label ${{vars.CHERRY_PICK_TESTING_IN_PROGRESS}} \
          ${{env.PR_NUMBER}} || :

  CherryPickTestMatrix:
    needs: IdentifyBranches
    if: ${{ needs.IdentifyBranches.outputs.branch_count > 0 && ( success() || failure() ) }}
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJSON(needs.IdentifyBranches.outputs.branches) }}
    uses: ./.github/workflows/AsteriskUnitGateTest.yml
    with:
      test_type:         cherry-pick
      asterisk_repo:     ${{github.repository}}
      pr_number:         ${{github.event.number}}
      base_branch:       ${{matrix.branch}}
      is_cherry_pick:    true
      build_options:     ${{vars.BUILD_OPTIONS}}
      unittest_command:  ${{vars.UNITTEST_COMMAND}}
      testsuite_repo:    ${{vars.TESTSUITE_REPO}}
      gatetest_list:     ${{vars.GATETEST_LIST}}
      gatetest_commands: ${{vars.GATETEST_COMMANDS}}
    secrets: inherit

  CherryPickTestResults:
    needs: [ IdentifyBranches, CherryPickTestMatrix ]
    if: ${{ needs.IdentifyBranches.outputs.branch_count > 0 && ( success() || failure() ) }}
    runs-on: ubuntu-latest
    steps:
      - name: Check test matrix status
        env:
          RESULT:    ${{needs.CherryPickTestMatrix.result}}
          GH_TOKEN:  ${{ secrets.TOKEN }}
        run: |
          case $RESULT in
            success)
              gh pr edit --repo ${{github.repository}} \
                --remove-label ${{vars.CHERRY_PICK_TESTING_IN_PROGRESS}} \
                --add-label ${{vars.CHERRY_PICK_CHECKS_PASSED_LABEL}} \
                ${{env.PR_NUMBER}} || :
              echo "::notice::All tests passed"
              exit 0
              ;;
            skipped)
              gh pr edit --repo ${{github.repository}} \
                --remove-label ${{vars.CHERRY_PICK_TESTING_IN_PROGRESS}} \
                --add-label ${{vars.CHERRY_PICK_CHECKS_FAILED_LABEL}} \
                ${{env.PR_NUMBER}} || :
              echo "::notice::Unit tests were skipped because of an earlier failure"
              exit 1
              ;;
            *)
              gh pr edit --repo ${{github.repository}} \
                --remove-label ${{vars.CHERRY_PICK_TESTING_IN_PROGRESS}} \
                --add-label ${{vars.CHERRY_PICK_CHECKS_FAILED_LABEL}} \
                ${{env.PR_NUMBER}} || :
              echo "::error::One or more tests failed ($RESULT)"
              exit 1
          esac

