name: AsteriskPRAction
on:
  workflow_call:

jobs:
  _PRCheck:
    name: "check"
    if: ${{ (github.event.action != 'labeled') || (github.event.action == 'labeled' && github.event.label.name == vars.RECHECKPR_LABEL) }}
    concurrency:
      group: check-${{ github.triggering_actor }}-${{ github.head_ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/AsteriskPRCheck.yml

  _PRCPCheck:
    name: "cpcheck"
    if: ${{ github.event.label.name == vars.CHERRY_PICK_TEST_LABEL }}
    concurrency:
      group: cpcheck-${{ github.triggering_actor }}-${{ github.head_ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/AsteriskPRCPCheck.yml

  _PRMerge:
    name: "merge"
    if: contains(fromJSON(vars.MERGE_APPROVED_LABELS), github.event.label.name)
    concurrency:
      group: merge-${{ github.triggering_actor }}-${{ github.head_ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/AsteriskPRMerge.yml
