name: UnitGateTest
on:
  workflow_call:
    inputs:
      test_type:
        description: 'weekly, nightly, prstatechange, prrecheck, cherry-pick, mergepr'
        required: true
        type: string
      asterisk_repo:
        required: true
        type: string
      pr_number:
        required: true
        type: string
      base_branch:
        required: true
        type: string
      is_cherry_pick:
        required: false
        type: boolean
        default: false
      build_script:
        required: false
        type: string
        default: "buildAsterisk.sh"
      build_options:
        required: false
        type: string
        default: ""
      output_cache_dir:
        required: false
        type: string
        default: cache
      build_cache_dir:
        required: false
        type: string
        default: build-cache
      modules_blacklist:
        type: string
        default: ""
        required: false
      unittest_command:
        type: string
        required: true
      testsuite_repo:
        type: string
        required: false
        default: asterisk/testsuite
      testsuite_test_pr:
        type: string
        required: false
      gatetest_list:
        type: string
        required: true
      gatetest_commands:
        type: string
        required: true
      user_group:
        required: false
        type: string
      realtime:
        type: boolean
        required: false
        default: false

jobs:
  Build:
    uses: ./.github/workflows/AsteriskBuildAndCache.yml
    with:
      test_type:         ${{ inputs.test_type }}
      asterisk_repo:     ${{ inputs.asterisk_repo }}
      pr_number:         ${{ inputs.pr_number }}
      base_branch:       ${{ inputs.base_branch }}
      is_cherry_pick:    ${{ inputs.is_cherry_pick }}
      build_options:     ${{ inputs.build_options }}
      modules_blacklist: ${{ inputs.modules_blacklist }}
      build_cache_dir:   ${{ inputs.build_cache_dir }}
      build_cache_key:   ${{ github.workflow }}-${{ github.run_number }}-${{ inputs.pr_number }}-${{ inputs.base_branch }}

  BuildNoDevmode:
    uses: ./.github/workflows/AsteriskBuildAndCache.yml
    with:
      job_name_extra:    -no-dev-mode
      test_type:         ${{ inputs.test_type }}
      asterisk_repo:     ${{ inputs.asterisk_repo }}
      pr_number:         ${{ inputs.pr_number }}
      base_branch:       ${{ inputs.base_branch }}
      is_cherry_pick:    ${{ inputs.is_cherry_pick }}
      build_options:     ${{ inputs.build_options }} --compile-double --no-dev-mode
      no_alembic:        true
      modules_blacklist: ${{ inputs.modules_blacklist }}
      build_cache_dir:

  Unit:
    needs: Build
    uses: ./.github/workflows/AsteriskRunUnitTests.yml
    with:
      test_type:         ${{ inputs.test_type }}
      base_branch:       ${{ inputs.base_branch }}
      user_group:        ${{ inputs.user_group }}
      unittest_command:  ${{ inputs.unittest_command }}
      output_cache_dir:  ${{ inputs.output_cache_dir }}
      build_cache_dir:   ${{ inputs.build_cache_dir }}
      build_cache_key:   ${{ github.workflow }}-${{ github.run_number }}-${{ inputs.pr_number }}-${{ inputs.base_branch }}

  Gate:
    needs: Build
    name: Gate
    if: ${{ inputs.gatetest_list != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        group: ${{ fromJSON(inputs.gatetest_list) }}
    uses: ./.github/workflows/AsteriskRunGateTests.yml
    with:
      test_type:         ${{ inputs.test_type }}
      base_branch:       ${{ inputs.base_branch }}
      user_group:        ${{ inputs.user_group }}
      testsuite_repo:    ${{ inputs.testsuite_repo }}
      testsuite_test_pr: ${{ inputs.testsuite_test_pr }}
      gatetest_group:    ${{ matrix.group }}
      gatetest_commands: ${{ inputs.gatetest_commands }}
      build_cache_dir:   ${{ inputs.build_cache_dir }}
      build_cache_key:   ${{ github.workflow }}-${{ github.run_number }}-${{ inputs.pr_number }}-${{ inputs.base_branch }}
      realtime:          ${{ inputs.realtime }}

