name: AsteriskRecheckPR
run-name: "${{github.workflow}}-${{github.event.label.name}}-${{github.event.number}}"
on:
  workflow_call:
    secrets:
      TOKEN:
        required: true

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set Label
        id: setlabel
        env:
          GH_TOKEN:  ${{ secrets.TOKEN }}
        run: | 
          gh pr edit --repo ${{github.repository}} \
            --remove-label ${{vars.RECHECKPR_LABEL}} \
            --remove-label ${{vars.PR_SUBMIT_TESTS_PASSED}} \
            --remove-label  ${{vars.PR_SUBMIT_TESTS_FAILED}} \
            --add-label ${{vars.PR_SUBMIT_TESTING_IN_PROGRESS}} \
            $PR_NUMBER || :

  PRCheck:
    name: PRCheck
    uses: ./.github/workflows/AsteriskUnitGateTest.yml
    with:
      test_type:         prrecheck
      asterisk_repo:     ${{github.repository}}
      pr_number:         ${{github.event.number}}
      base_branch:       ${{github.event.pull_request.base.ref}}
      is_cherry_pick:    false
      build_options:     ${{vars.BUILD_OPTIONS}}
      unittest_command:  ${{vars.UNITTEST_COMMAND}}
      testsuite_repo:    ${{vars.TESTSUITE_REPO}}
      gatetest_list:     ${{vars.GATETEST_LIST}}
      gatetest_commands: ${{vars.GATETEST_COMMANDS}}
    secrets: inherit

  TestResults:
    if: always()
    runs-on: ubuntu-latest
    needs: [PRCheck]
    steps:
      - name: Check status
        env:
          GH_TOKEN:  ${{ secrets.TOKEN }}
          RESULT_UNIT: ${{ needs.PRCheck.result }}
          TESTS_PASSED: ${{ vars.PR_SUBMIT_TESTS_PASSED }}
          TESTS_FAILED: ${{ vars.PR_SUBMIT_TESTS_FAILED }}
        run: |
          declare -i rc=0
          echo "all results: ${{ toJSON(needs.*.result) }}"
          case $RESULT_UNIT in
            success)
              echo "::notice::Unit/Gate tests passed"
              ;;
            skipped)
              echo "::error::Unit/Gate tests were skipped because of an earlier failure"
              rc+=1
              ;;
            *)
              echo "::error::One or more Unit/Gate tests failed ($RESULT_UNIT)"
              rc+=1
          esac
          
          label=$TESTS_PASSED
          if [ $rc != 0 ] ; then
            label=$TESTS_FAILED
          fi
          gh pr edit --repo ${{github.repository}} \
            --remove-label ${{vars.PR_SUBMIT_TESTING_IN_PROGRESS}} \
            --add-label $label \
              $PR_NUMBER || :
          exit $rc
