name: NightlyTest
on:
  workflow_call:
    inputs:
      test_type:
        description: 'weekly, nightly, prstatechange, prrecheck, cherry-pick'
        type: string
        required: false
        default: nightly
      branches:
        required: true
        type: string
        description: "Array of branches to run: ['21','master']."
      group_list:
        required: false
        type: string
        description: "Array of test groups to run: ['ari1','channels']."
      realtime:
        type: boolean
        required: false
        default: false
    secrets:
      TOKEN:
        required: true

jobs:

  Test:
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJSON(inputs.branches) }}
    uses: ./.github/workflows/AsteriskUnitGateTest.yml
    with:
      test_type:         ${{ inputs.test_type }}
      asterisk_repo:     ${{ github.repository }}
      pr_number:         0
      base_branch:       ${{ matrix.branch }}
      is_cherry_pick:    false
      build_options:     ${{ vars.BUILD_OPTIONS }}
      unittest_command:  ${{ vars.UNITTEST_COMMAND }}
      testsuite_repo:    ${{ vars.TESTSUITE_REPO }}
      gatetest_list:     ${{ inputs.group_list }}
      gatetest_commands: ${{ vars.GATETEST_COMMANDS }}
      realtime:          ${{ inputs.realtime }}
    secrets: inherit

  Cleanup:
    needs: [ Test ]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - env:
          RESULT:    ${{ needs.Test.result }}
        run: |
          case $RESULT in
            success)
              echo "All tests passed"
              exit 0
              ;;
            skipped)
              echo "One or more tests were skipped because of an earlier failure"
              exit 1
              ;;
            *)
              echo "One or more tests failed ($RESULT)"
              exit 1
          esac

