name: CreatePrivateFork
run-name: "CreatePrivateFork"
on:
  workflow_dispatch:
    inputs:
      src_repo:
        description: 'Source asterisk org repo:'
        required: true
        type: string
      dst_repo:
        description: 'Destination asterisk org repo:'
        required: true
        type: string

jobs:
  CreatePrivateFork:
    runs-on: ubuntu-latest
    steps:
      - name: CreateFork
        uses: asterisk/asterisk-ci-actions/CreatePrivateFork@main
        with:
          src_repo:         ${{ inputs.src_repo }}
          dst_repo:         ${{ inputs.dst_repo }}
          github_token:     ${{ secrets.ASTERISKTEAM_PAT }}

      - name: CopyVars
        uses: asterisk/asterisk-ci-actions/CopyRepoVariables@main
        with:
          src_repo:        ${{ inputs.src_repo }}
          dst_repo:        ${{ inputs.dst_repo }}
          github_token:    ${{ secrets.ASTERISKTEAM_PAT }}

  UpdateControlData:
    needs: CreatePrivateFork
    uses: ./.github/workflows/UpdateControlData.yml
    with:
      repo: ${{ inputs.dst_repo }}
    secrets: inherit

