name: PRLabeled
# WARNING!  The run name MUST start with "PR <pr_number>".
# The accompanying privleged workflow parses this to find
# the PR number.  It's the only reliable way it can get it.
run-name: "PR ${{ github.event.number }} Labeled by ${{ github.actor }}"
on:
  pull_request:
    types: [ opened,synchronize,labeled ]

jobs:
  Setup:
    name: ${{inputs.jobname}}-Job1
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: DumpEnvironment
        uses: asterisk/asterisk-ci-actions/DumpEnvironmentAction@main

  TestCalled:
    concurrency:
      group: check-${{ github.triggering_actor }}-${{ github.head_ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/TestCalledWorkflow.yml
    with:
      jobname:  AAAA
