name: 'RAUT'
on:
  workflow_call:
    inputs:
      test_type:
        required: true
        type: string
      base_branch:
        required: true
        type: string
      user_group:
        type: string
        required: false
        default: asteriskci:users
      unittest_command:
        type: string
        required: true
      output_cache_dir:
        type: string
        required: false
        default: cache
      build_cache_dir:
        type: string
        required: false
        default: build-cache
      build_cache_key:
        type: string
        required: true

jobs:
  RunUnitTests:
    name: UnitTests ${{ inputs.base_branch }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/asterisk/asteriskci-agent-rocky8:latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Restore Asterisk Cache
        uses: asterisk/asterisk-ci-actions/RestoreAsteriskFromCache@main-cache-builds
        with:
          build_cache_dir: ${{inputs.build_cache_dir}}
          build_cache_key: ${{inputs.build_cache_key}}
          user_group: ${{inputs.user_group}}

      - name: Setup
        env:
          GH_TOKEN: ${{secrets.TOKEN}}
          GITHUB_TOKEN: ${{secrets.TOKEN}}
          BASE_BRANCH: ${{ inputs.base_branch }}
          ACTION_DIR: asterisk-ci-actions
        run: |
          UNIT_TEST_NAME="${{inputs.test_type}}-unit-${BASE_BRANCH//\//-}"
          echo "UNIT_TEST_NAME=${UNIT_TEST_NAME}" >> "${GITHUB_ENV}"

          cd ${GITHUB_WORKSPACE}
          ls -al
          
          echo "*** Cloning asterisk/${ACTION_DIR}"
          git clone ${GITHUB_SERVER_URL}/asterisk/${ACTION_DIR}
          git -C ${ACTION_DIR} checkout main-cache-builds

      - name: Run Unit Tests
        env:
          GH_TOKEN: ${{secrets.TOKEN}}
          GITHUB_TOKEN: ${{secrets.TOKEN}}
          UNITTEST_COMMAND: ${{ inputs.unittest_command }}
          CACHE_DIR: ${{inputs.output_cache_dir}}
          USER_GROUP: ${{ inputs.user_group }}
          ACTION_DIR: asterisk-ci-actions
        run: |
          cd ${GITHUB_WORKSPACE}
          export SCRIPT_DIR=${GITHUB_WORKSPACE}/${ACTION_DIR}/scripts
          export OUTPUT_DIR=${GITHUB_WORKSPACE}/${CACHE_DIR}/output
          
          ${SCRIPT_DIR}/runAsteriskUnitTests.sh --no-expect --github \
            --user-group=${USER_GROUP} \
            --output-dir=${OUTPUT_DIR} \
            --output-xml=${OUTPUT_DIR}/unittests-results.xml \
            --unittest-command="${UNITTEST_COMMAND}"

      - name: Save Output
        id: save-output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.UNIT_TEST_NAME}}
          path: ${{inputs.output_cache_dir}}/output

