name: 'RAUT'
on:
  workflow_call:
    inputs:
      test_type:
        required: true
        type: string
      base_branch:
        required: true
        type: string
      user_group:
        type: string
        required: false
        default: asteriskci:users
      unittest_command:
        type: string
        required: true
      output_cache_dir:
        type: string
        required: false
        default: cache
      build_cache_dir:
        type: string
        required: false
        default: build-cache
      build_cache_key:
        type: string
        required: true

jobs:
  RunUnitTests:
    name: UnitTests ${{ inputs.base_branch }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/asterisk/asteriskci-agent-rocky8:latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Restore Asterisk Cache
        uses: asterisk/asterisk-ci-actions/RestoreAsteriskFromCache@main-cache-builds
        with:
          build_cache_dir: ${{inputs.build_cache_dir}}
          build_cache_key: ${{inputs.build_cache_key}}
          user_group: ${{inputs.user_group}}

      - name: Setup
        env:
          GH_TOKEN: ${{secrets.TOKEN}}
          GITHUB_TOKEN: ${{secrets.TOKEN}}
          CACHE_DIR: ${{inputs.output_cache_dir}}
          BASE_BRANCH: ${{ inputs.base_branch }}
        run: |
          BASE_BRANCH="${{inputs.base_branch}}"
          UNIT_TEST_NAME="${{inputs.test_type}}-unit-${BASE_BRANCH//\//-}"
          echo "UNIT_TEST_NAME=${UNIT_TEST_NAME}" >> "${GITHUB_ENV}"
          export GITHUB_ACTION_REPOSITORY=asterisk/asterisk-ci-actions
          echo "GITHUB_ACTION_REPOSITORY=${GITHUB_ACTION_REPOSITORY}" >> "${GITHUB_ENV}"
          export ACTION_DIR=$(basename ${GITHUB_ACTION_REPOSITORY})
          echo "ACTION_DIR=${ACTION_DIR}" >> "${GITHUB_ENV}"
          export SCRIPT_DIR=${GITHUB_WORKSPACE}/${ACTION_DIR}/scripts
          echo "SCRIPT_DIR=${SCRIPT_DIR}" >> "${GITHUB_ENV}"
          export OUTPUT_DIR=${GITHUB_WORKSPACE}/${CACHE_DIR}/output
          echo "OUTPUT_DIR=${OUTPUT_DIR}" >> "${GITHUB_ENV}"
          cd ${GITHUB_WORKSPACE}
          ls -al
          
          echo "*** Cloning ${GITHUB_ACTION_REPOSITORY}"
          git clone ${GITHUB_SERVER_URL}/${GITHUB_ACTION_REPOSITORY}
          git -C ${ACTION_DIR} checkout main-cache-builds
          mkdir -p ${OUTPUT_DIR}
          cd build-cache
          sudo rsync -aH . /
          chown -R asteriskci:users /etc/asterisk /var/{cache,lib,log,spool}/asterisk

      - name: Run Unit Tests
        env:
          GH_TOKEN: ${{secrets.TOKEN}}
          GITHUB_TOKEN: ${{secrets.TOKEN}}
          UNITTEST_COMMAND: ${{ inputs.unittest_command }}
          USER_GROUP: ${{ inputs.user_group }}
        run: |
          cd ${GITHUB_WORKSPACE}
          ${SCRIPT_DIR}/runAsteriskUnitTests.sh --no-expect --github \
            --user-group=${USER_GROUP} \
            --output-dir=${OUTPUT_DIR} \
            --output-xml=${OUTPUT_DIR}/unittests-results.xml \
            --unittest-command="${UNITTEST_COMMAND}"

      - name: Save Output
        id: save-output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.UNIT_TEST_NAME}}
          path: ${{inputs.output_cache_dir}}/output

