name: 'RunCherryPickPrelimTest'
on:
  workflow_call:
    inputs:
      actions_ref:
        description: 'JSON object reference to the actions: { "owner": "asterisk", "repo": "asterisk-ci-actions", "branch": "main" }'
        type: string
        required: false
        default: '{ "owner": "asterisk", "repo": "asterisk-ci-actions", "branch": "main" }'
      repo:
        required: true
        type: string
      pr_number:
        required: true
        type: string
      base_branch:
        required: true
        type: string
    secrets:
      TOKEN:
        required: true

env:
  GH_TOKEN:     ${{ secrets.TOKEN }}
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  REPO:         ${{ inputs.repo }}
  PR_NUMBER:    ${{ inputs.pr_number }}
  BASE_BRANCH:  ${{ inputs.base_branch }}
  REPO_DIR:     ${{ github.event.repository.name }}
  REPO_ORG:     ${{ github.event.repository.owner.login }}
  ACTIONS_OWNER:    ${{ fromJSON(inputs.actions_ref).owner }}
  ACTIONS_REPO:     ${{ fromJSON(inputs.actions_ref).repo }}
  ACTIONS_BRANCH:   ${{ fromJSON(inputs.actions_ref).branch }}
  SCRIPT_DIR:       ${{ github.workspace }}/asterisk-ci-actions/scripts

jobs:
  CherryPick:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Setup Runner
        run: |
          # Setup
          wget -qO asterisk-ci-actions.tar.gz \
            https://github.com/${ACTIONS_OWNER}/${ACTIONS_REPO}/archive/refs/heads/${ACTIONS_BRANCH}.tar.gz
          tar -xf asterisk-ci-actions.tar.gz --transform="s/^${ACTIONS_REPO}-${ACTIONS_BRANCH}/asterisk-ci-actions/g"

      - name: Run Cherry Pick
        run: |
          # Cherry Pick
          mkdir -p ${REPO_DIR}

          echo "*** Checking out ${ASTERISK_REPO}"
          ${SCRIPT_DIR}/cherryPick.sh --repo=${REPO} \
            --pr-number=${PR_NUMBER} --branch=${BASE_BRANCH} \
            --repo-dir=${REPO_DIR}
