name: 'RunCherryPickPrelimTest'
on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      pr_number:
        required: true
        type: string
      base_branch:
        required: true
        type: string
    secrets:
      TOKEN:
        required: true

env:
  GH_TOKEN:     ${{secrets.TOKEN}}
  GITHUB_TOKEN: ${{secrets.TOKEN}}
  REPO:         ${{inputs.repo}}
  PR_NUMBER:    ${{inputs.pr_number}}
  BASE_BRANCH:  ${{inputs.base_branch}}
  ACTION_DIR:   asterisk-ci-actions
  SCRIPT_DIR:   ${{github.workspace}}/asterisk-ci-actions/scripts
  REPO_DIR:     ${{github.event.repository.name}}
  REPO_ORG:     ${{github.event.repository.owner.login}}
  CI_BRANCH:    main-cache-builds

jobs:
  CherryPick:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Run Cherry Pick
        run: |
          echo "*** Cloning ${REPO_ORG}/${ACTION_DIR}"
          git clone ${GITHUB_SERVER_URL}/${REPO_ORG}/${ACTION_DIR}
          git -C ${ACTION_DIR} checkout ${CI_BRANCH:-main}

          mkdir -p ${REPO_DIR}

          echo "*** Checking out ${ASTERISK_REPO}"
          ${SCRIPT_DIR}/cherryPick.sh --repo=${REPO} \
            --pr-number=${PR_NUMBER} --branch=${BASE_BRANCH} \
            --repo-dir=${REPO_DIR}
