name: TestWorkflow
run-name: "TestWorkflow"
on:
  workflow_dispatch:
    inputs:
      branches:
        description: "JSON array of branches: ['18','20'] (no spaces) or leave blank for all current branches."
        required:    false
        type:        string

env:
  FROM_WF: "from workflow"

jobs:
  Job1:
    runs-on: ubuntu-latest
    env:
      FROM_JOB: "from job"
    defaults:
      run:
        shell: bash
    steps:
      - name: Send Release Announcements SES no envelope
        if: true
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: email-smtp.us-east-1.amazonaws.com
          server_port: 587
          secure: false
          username: ${{ secrets.ASTERISKTEAM_SES_KEY_ID }}
          password: ${{ secrets.ASTERISKTEAM_SES_KEY_SECRET }}
          subject: Test via SES
          to: gjoseph@sangoma.com
          from: Asterisk Team <asteriskteam@sangoma.com>
          body: "test email"
          reply_to: no-reply+asteriskteam@sangoma.com
          ignore_cert: true
          convert_markdown: false
          nodemailerlog: true
          nodemailerdebug: true

      - name: Send Release Announcements SES no envelope2
        if: false
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: email-smtp.us-east-1.amazonaws.com
          server_port: 587
          secure: false
          username: ${{ secrets.ASTERISKTEAM_SES_KEY_ID }}
          password: ${{ secrets.ASTERISKTEAM_SES_KEY_SECRET }}
          subject: Test via SES
          to: gjoseph@sangoma.com
          from: asteriskteam@sangoma.com
          body: "test email"
          reply_to: no-reply@sangoma.com
          ignore_cert: true
          convert_markdown: false
          nodemailerlog: true
          nodemailerdebug: true

      - name: Send Release Announcements SES no envelope3
        if: false
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: email-smtp.us-east-1.amazonaws.com
          server_port: 587
          secure: false
          username: ${{ secrets.ASTERISKTEAM_SES_KEY_ID }}
          password: ${{ secrets.ASTERISKTEAM_SES_KEY_SECRET }}
          subject: Test via SES
          to: gjoseph@sangoma.com
          from: <asteriskteam@sangoma.com>
          body: "test email"
          reply_to: no-reply@sangoma.com
          ignore_cert: true
          convert_markdown: false
          nodemailerlog: true
          nodemailerdebug: true

      - name: Send Release Announcements SES envelope_from
        if: false
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: email-smtp.us-east-1.amazonaws.com
          server_port: 587
          secure: false
          username: ${{ secrets.ASTERISKTEAM_SES_KEY_ID }}
          password: ${{ secrets.ASTERISKTEAM_SES_KEY_SECRET }}
          subject: Test via SES
          to: gjoseph@sangoma.com
          from: Asterisk Team #<asteriskteam@sangoma.com>
          envelope_from: asteriskteam@sangoma.com
          body: "test email"
          reply_to: no-reply@sangoma.com
          ignore_cert: true
          convert_markdown: false
          nodemailerlog: true
          nodemailerdebug: true

      - name: Send Release Announcements SES envelope_from2
        if: false
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: email-smtp.us-east-1.amazonaws.com
          server_port: 587
          secure: false
          username: ${{ secrets.ASTERISKTEAM_SES_KEY_ID }}
          password: ${{ secrets.ASTERISKTEAM_SES_KEY_SECRET }}
          subject: Test via SES
          to: gjoseph@sangoma.com
          from: Asterisk Team <asteriskteam@sangoma.com>
          envelope_from: asteriskteam@sangoma.com
          body: "test email"
          reply_to: no-reply@sangoma.com
          ignore_cert: true
          convert_markdown: false
          nodemailerlog: true
          nodemailerdebug: true

      - name: Send Release Announcements SES envelope_to
        if: false
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: email-smtp.us-east-1.amazonaws.com
          server_port: 587
          secure: false
          username: ${{ secrets.ASTERISKTEAM_SES_KEY_ID }}
          password: ${{ secrets.ASTERISKTEAM_SES_KEY_SECRET }}
          subject: Test via SES
          to: gjoseph@sangoma.com
          from: Asterisk Team <asteriskteam@sangoma.com>
          envelope_from: Asterisk Team <asteriskteam@sangoma.com>
          envelope_to: George Joseph <gjoseph@sangoma.com>
          body: "test email"
          reply_to: no-reply@sangoma.com
          ignore_cert: true
          convert_markdown: false
          nodemailerlog: true
          nodemailerdebug: true

      - name: Send Release Announcements SES envelope_to/from
        if: false
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: email-smtp.us-east-1.amazonaws.com
          server_port: 587
          secure: false
          username: ${{ secrets.ASTERISKTEAM_SES_KEY_ID }}
          password: ${{ secrets.ASTERISKTEAM_SES_KEY_SECRET }}
          subject: Test via SES
          to: gjoseph@sangoma.com
          from: Asterisk Team <asteriskteam@sangoma.com>
          envelope_from: asteriskteam@sangoma.com
          envelope_to: gjoseph@sangoma.com
          body: "test email"
          reply_to: no-reply@sangoma.com
          ignore_cert: true
          convert_markdown: false
          nodemailerlog: true
          nodemailerdebug: true

      - name: Send Release Announcements GMAIL no envelope
        if: false
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: false
          username: asteriskteamsa@sangoma.com
          password: ${{secrets.ASTERISKTEAMSA_GMAIL_TOKEN}}
          subject: Test via GMAIL
          to: gjoseph@sangoma.com
          from: asteriskteamsa@sangoma.com
          body: "test email"
          reply_to: no-reply@sangoma.com
          ignore_cert: true
          convert_markdown: false
          nodemailerlog: true
          nodemailerdebug: true

      - name: Send Release Announcements GMAIL envelope_from
        if: false
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: false
          username: asteriskteamsa@sangoma.com
          password: ${{secrets.ASTERISKTEAMSA_GMAIL_TOKEN}}
          subject: Test via GMAIL
          to: gjoseph@sangoma.com
          from: Asterisk Team
          envelope_from: asteriskteamsa@sangoma.com
          body: "test email"
          reply_to: no-reply@sangoma.com
          ignore_cert: true
          convert_markdown: false
          nodemailerlog: true
          nodemailerdebug: true

      - name: Send Release Announcements GMAIL envelope_to
        if: false
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: false
          username: asteriskteamsa@sangoma.com
          password: ${{secrets.ASTERISKTEAMSA_GMAIL_TOKEN}}
          subject: Test via GMAIL
          to: gjoseph@sangoma.com
          from: Asterisk Team <asteriskteamsa@sangoma.com>
          envelope_to: gjoseph@sangoma.com
          body: "test email"
          reply_to: no-reply@sangoma.com
          ignore_cert: true
          convert_markdown: false
          nodemailerlog: true
          nodemailerdebug: true
          
      - name: Send Release Announcements GMAIL envelope_to/from
        if: false
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 587
          secure: false
          username: asteriskteamsa@sangoma.com
          password: ${{secrets.ASTERISKTEAMSA_GMAIL_TOKEN}}
          subject: Test via GMAIL
          to: gjoseph@sangoma.com
          from: Asterisk Team <asteriskteamsa@sangoma.com>
          envelope_from: asteriskteamsa@sangoma.com
          envelope_to: gjoseph@sangoma.com
          body: "test email"
          reply_to: no-reply@sangoma.com
          ignore_cert: true
          convert_markdown: false
          nodemailerlog: true
          nodemailerdebug: true
          