name: TestWorkflow
run-name: "TestWorkflow"
on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'nightly, prsubmit, cherry-pick'
        required: true
        type: string
      asterisk_repo:
        description: 'Must be org/repo'
        required: true
        type: string
      pr_number:
        required: true
        type: number
      base_branch:
        required: true
        type: string

env:
  TEST_TYPE:     ${{inputs.test_type}}
  ASTERISK_REPO: ${{inputs.asterisk_repo}}
  PR_NUMBER:     ${{inputs.pr_number}}
  BRANCH:        ${{inputs.base_branch}}

jobs:
  AsteriskCheckPR:
    name: AsteriskCheckPR
    uses: ./.github/workflows/AsteriskCheckPRforBranch.yml
    with:
      test_type: ${{ inputs.test_type }}
      asterisk_repo: ${{ inputs.asterisk_repo }}
      pr_number:  ${{ inputs.pr_number }}
      base_branch: ${{ inputs.base_branch }}
    secrets:
      ASTERISKTEAM_PAT: ${{ secrets.ASTERISKTEAM_PAT }}
