name: TestWorkflow
run-name: "TestWorkflow"
on:
  workflow_dispatch:
    inputs:
      counter:
        type: number
        default: 0

env:
  COUNTER: 42

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: DumpEnvironment
        uses: asterisk/asterisk-ci-actions/DumpEnvironmentAction@main
        with:
          action-inputs: ${{ toJSON(inputs) }}

  SetupMatrix:
#    if: ${{ inputs.counter == 666 }}
#    needs: Setup 
    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        group: ['A','B']
    steps:
      - name: DoSomething
        shell: bash
        run: |
          echo "I DID SOMETHING FIRST"

  Setup2:
#    needs: SetupMatrix 
    runs-on: ubuntu-latest
    steps:
      - name: DoSomething
        shell: bash
        run: |
          echo "I DID SOMETHING AFTER"


#  TestCalledWorkflow:
#    uses: ./.github/workflows/TestCalledWorkflow.yml
#    with:
#      counter: ${{inputs.counter}}

