name: TestWorkflow
run-name: "TestWorkflow"
on:
  workflow_dispatch:
    inputs:
      branches:
        description: "JSON array of branches: ['18','20'] (no spaces) or leave blank for all current branches."
        required:    false
        type:        string

env:
  ACTIONS_OWNER:     asterisk
  ACTIONS_REPO:      asterisk-ci-actions
  ACTIONS_BRANCH:    main-test-native
  SCRIPT_DIR:        ${{ github.workspace }}/asterisk-ci-actions/scripts
  GH_TOKEN:          ${{secrets.GITHUB_TOKEN}}
  RUN_ID:            ${{ github.id }}
  WIKIDOC_BRANCHES:  ${{ inputs.branches || vars.WIKIDOC_BRANCHES }}

jobs:
  Job1:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: DumpEnvironment
        uses: asterisk/asterisk-ci-actions/DumpEnvironmentAction@main
        with:
          save_output: true

      - name: test
        run: |
          echo "BRANCHES: ${WIKIDOC_BRANCHES}"
