name: PRCheck
on:
  workflow_call:

permissions:
  actions: write
  checks: read
  contents: read
  issues: read
  pull-requests: write
  repository-projects: read
  statuses: read

env:
  REPO:            ${{ github.repository }}
  REPO_DIR:        ${{ github.workspace }}/${{ github.event.repository.name }}
  REPO_ORG:        ${{ github.event.repository.owner.login }}
  PR_NUMBER:       ${{ github.event.number }}
  BASE_BRANCH:     ${{ github.event.pull_request.base.ref }}
  WORKFLOW_NAME:   ${{ github.workflow }}
  WORKFLOW_RUN_ID: ${{ github.run_id }}
  GH_TOKEN:        ${{ secrets.GITHUB_TOKEN }}
  LOG_DIR:         ${{ github.workspace }}/logs
  LOG_FILE:        ${{ github.workspace }}/logs/job_summary.txt
  TRIGGER:         ${{ github.event.action }}
  TESTING_IN_PROGRESS: ${{ vars.PR_SUBMIT_TESTING_IN_PROGRESS }}
  TESTS_PASSED:        ${{ vars.PR_SUBMIT_TESTS_PASSED }}
  TESTS_FAILED:        ${{ vars.PR_SUBMIT_TESTS_FAILED }}
  RECHECKPR_LABEL:     ${{ vars.RECHECKPR_LABEL }}
  ASTERISK_REPO:       ${{ vars.ASTERISK_REPO }}
  PR_STATE_CHANGE_DELAY_SEC:  ${{ vars.PR_STATE_CHANGE_DELAY_SEC || 120 }}
  ASSOCIATED_TEST_PR_REGEX:   ${{ vars.ASSOCIATED_TEST_PR_REGEX }}

jobs:
  Setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    outputs:
      asterisk_test_pr:  ${{ steps.setup.outputs.ASSOCIATED_TEST_PR }}
      gatetest_count:    ${{ steps.checkfiles.outputs.gatetest_count }}
      gatetest_group:    ${{ steps.checkfiles.outputs.gatetest_group }}
      gatetest_commands: ${{ steps.checkfiles.outputs.gatetest_commands }}
    steps:
      - name: GetActionsRepo
        uses: asterisk/asterisk-ci-actions/GetActionsRepo@main

      - name: Setup
        id: setup
        run: |
          if [ "$TRIGGER" != "labeled" ] ; then
            # Wait to allow time to add associated PR
            echo "Waiting for ${PR_STATE_CHANGE_DELAY_SEC} seconds to give user a chance to add PR comments"
            sleep ${PR_STATE_CHANGE_DELAY_SEC}
          fi

          # Label and get Asterisk PR
          gh pr edit --repo ${REPO} \
            --remove-label ${RECHECKPR_LABEL} \
            --remove-label ${TESTS_PASSED} \
            --remove-label ${TESTS_FAILED} \
            --add-label ${TESTING_IN_PROGRESS} \
            ${PR_NUMBER} || :

          # Asterisk PR will be placed in ASSOCIATED_TEST_PR in both
          # GITHUB_ENV and GITHUB_OUTPUT by the script.
          ${SCRIPT_DIR}/getAssociatedTestPR.sh \
            --repo=${REPO} \
            --pr-number=${PR_NUMBER} \
            --associated-test-pr-regex="${ASSOCIATED_TEST_PR_REGEX}"

      - name: Check if any tests have changed
        id: checkfiles
        run: |
          # Get files from PR
          # sets gatetest_count, gatetest_group and gatetest_commands
          ${SCRIPT_DIR}/getChangedTestsuiteTests.sh \
            --repo=${REPO} \
            --pr-number=${PR_NUMBER}

  UnitTest:
    name: UnitTest
    needs: [ Setup ]
    permissions:
      actions: read
      checks: read
      contents: read
      issues: read
      pull-requests: read
      statuses: read
    uses: ./.github/workflows/TestsuiteRunUnitTests.yml
    with:
      pr_number:         ${{ github.event.number }}
      base_branch:       ${{ github.event.pull_request.base.ref }}
      unittest_command:  ${{ vars.UNITTEST_COMMAND }}

  GateTest:
    name: GateTest
    needs: [ Setup ]
    if: ${{ needs.Setup.outputs.gatetest_count > 0 }}
    permissions:
      actions: read
      checks: read
      contents: read
      issues: read
      pull-requests: read
      statuses: read
    uses: ./.github/workflows/TestsuiteRunGateTests.yml
    with:
      pr_number:         ${{ github.event.number }}
      base_branch:       ${{ github.event.pull_request.base.ref }}
      is_cherry_pick:    false
      asterisk_test_pr:  ${{ needs.Setup.outputs.asterisk_test_pr }}
      asterisk_repo:     ${{ vars.ASTERISK_REPO }}
      gatetest_group:    ${{ needs.Setup.outputs.gatetest_group }}
      gatetest_commands: ${{ needs.Setup.outputs.gatetest_commands }}
      sipp_version:      ${{ vars.SIPP_VERSION }}

  PostWorkflow:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [Setup,UnitTest,GateTest]
    env:
      RESULT_SETUP:  ${{ needs.Setup.result }}
      RESULT_UNIT:   ${{ needs.UnitTest.result }}
      RESULT_GATE:   ${{ needs.GateTest.result }}
    steps:
        # ACTIONS_PATH, SCRIPT_DIR, NORMALIZED_BRANCH env vars
      - name: GetActionsRepo
        uses: asterisk/asterisk-ci-actions/GetActionsRepo@main

      - name: Add labels, reminders and summary
        run: |

          label=""
          RESULT_FULL="${RESULT_SETUP}-${RESULT_UNIT}-${RESULT_GATE}"
          echo "Result: $RESULT_FULL"
          case $RESULT_FULL in
          success-success-success)
              echo "All passed"
              label=$TESTS_PASSED
              RESULT=success
              gh cache delete -R ${REPO} ${BUILD_CACHE_KEY} || :
              ;;
          *failure*)
              echo "at least one failure"
              label=$TESTS_FAILED
              RESULT=failure
              ;;
          *cancelled*)
              echo "at least one cancelled"
              gh cache delete -R ${REPO} ${BUILD_CACHE_KEY} || :
              RESULT=failure
              ;;
          *skipped*)
              echo "at least one skipped but others succeeded"
              label=$TESTS_PASSED
              RESULT=success
              ;;
          *)
              echo "unknown result"
              label=$TESTS_FAILED
              RESULT=failure
              ;;
          esac

          gh pr edit --repo ${REPO} \
            --remove-label ${TESTING_IN_PROGRESS} \
            ${label:+--add-label $label} \
              $PR_NUMBER || :

          if [[ $RESULT =~ (success|failure) ]] ; then
            ${SCRIPT_DIR}/PRChecks/addPRChecklistIfNeeded.sh \
              --repo=${REPO} \
              --pr-number=${PR_NUMBER}

            ${SCRIPT_DIR}/createJobSummary.sh \
              --result=${RESULT} \
              --repo=${REPO} \
              --workflow-name="${WORKFLOW_NAME}" \
              --pr-number=${PR_NUMBER} \
              --workflow-run=${WORKFLOW_RUN_ID} \
              --tmp-dir=./run-${WORKFLOW_RUN_ID} \
              --job-summary-output=job_summary.txt \
              --write-step-summary \
              --add-pr-comment \
              --verbose || :
          fi
          exit 0
