name: TestWorkflow
run-name: "TestWorkflow"
on:
  workflow_dispatch:
    inputs:
      branches:
        required: false
        type: string

  schedule:
    - cron: '0 2 * * *'

jobs:
  TestWorkflow:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
#        ports:
#          # Maps tcp port 5432 on service container to the host
#          - 5432:5432

    steps:
#      - name: Check out repository code
#        uses: actions/checkout@v4
#        with:
#          ref: test-actions
          

      - name: TestStep
        timeout-minutes: 1
        id: teststep
        shell: bash
        run: |
          pwd
          mount
          ls -al
          echo "Exiting with RC 0 (forced)"
          echo "result=success" >> $GITHUB_OUTPUT
          exit 0
    
      - name: TestCompositeAction
        uses: asterisk/asterisk-ci-actions/TestCompositeAction@main
        with:
          test_type: basic
