name: TestCalledWorkflow
run-name: "TestCalledWorkflow"
on:
  workflow_call:
    inputs:
      actions_ref:
        description: 'JSON object reference to the actions: { "owner": "asterisk", "repo": "asterisk-ci-actions", "branch": "main" }'
        type: string
        required: false
        default: '{ "owner": "asterisk", "repo": "asterisk-ci-actions", "branch": "main" }'
      jobname:
        type: string
        required: true

env:
  ACTIONS_OWNER:     asterisk
  ACTIONS_REPO:      asterisk-ci-actions
  ACTIONS_BRANCH:    main
  SCRIPT_DIR:        ${{ github.workspace }}/asterisk-ci-actions/scripts
  RUN_ID:            ${{ github.run_id }}

jobs:
  Job1:
    name: ${{inputs.jobname}}-Job1
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: DumpEnvironment
        uses: asterisk/asterisk-ci-actions/DumpEnvironmentAction@main
        with:
          artifact_id: DumpEnvironment-${{inputs.jobname}}-Job1

      - name: test
        run: |
          sleep 120
          exit 0

  Job2:
    runs-on: ubuntu-latest
    name: ${{inputs.jobname}}-Job2
    defaults:
      run:
        shell: bash
    steps:
      - name: test
        run: |
          sleep 120
          exit 0
