name: PRCPCheck
on:
  workflow_call:

permissions:
  actions: write
  checks: read
  contents: read
  issues: read
  pull-requests: write
  statuses: read

env:
  REPO:            ${{ github.repository }}
  REPO_DIR:        ${{ github.workspace }}/${{ github.event.repository.name }}
  REPO_ORG:        ${{ github.event.repository.owner.login }}
  PR_NUMBER:       ${{ github.event.number }}
  BASE_BRANCH:     ${{ github.event.pull_request.base.ref }}
  WORKFLOW_NAME:   ${{ github.workflow }}
  WORKFLOW_RUN_ID: ${{ github.run_id }}
  GH_TOKEN:        ${{ github.token }}
  LOG_DIR:         ${{ github.workspace }}/logs
  LOG_FILE:        ${{ github.workspace }}/logs/job_summary.txt
  TESTING_IN_PROGRESS: ${{ vars.CHERRY_PICK_TESTING_IN_PROGRESS }}
  TESTS_PASSED:        ${{ vars.CHERRY_PICK_CHECKS_PASSED_LABEL }}
  TESTS_FAILED:        ${{ vars.CHERRY_PICK_CHECKS_FAILED_LABEL }}

jobs:
  Setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      branches:           ${{ steps.setup.outputs.BRANCHES }}
      branch_count:       ${{ steps.setup.outputs.BRANCH_COUNT }}
      testsuite_test_pr:  ${{ steps.setup.outputs.TESTSUITE_TEST_PR }}
    steps:
        # ACTIONS_PATH, SCRIPT_DIR, NORMALIZED_BRANCH env vars
      - name: GetActionsRepo
        uses: asterisk/asterisk-ci-actions/GetActionsRepo@main

      - id: setup
        env:
          CHERRY_PICK_TEST_LABEL:          ${{ vars.CHERRY_PICK_TEST_LABEL }}
          CHERRY_PICK_REGEX:               ${{ vars.CHERRY_PICK_REGEX }}
        run: |

          gh pr edit --repo ${REPO} \
            --remove-label ${CHERRY_PICK_TEST_LABEL} \
            --remove-label ${TESTS_PASSED} \
            --remove-label ${TESTS_FAILED} \
            --remove-label ${TESTING_IN_PROGRESS} \
            ${PR_NUMBER} || :

          # The script will populate BRANCHES and BRANCH_COUNT in
          # both GITHUB_ENV and GITHUB_OUTPUT for future use but
          # we need them here as well so we need to capture and
          # parse the output.
          result=$(${SCRIPT_DIR}/getCherryPickBranchesFromPR.sh \
            --repo=${REPO} \
            --pr-number=${PR_NUMBER} \
            --cherry-pick-regex="${CHERRY_PICK_REGEX}")
          BRANCH_COUNT=$(echo ${result} | jq -c '.branch_count')
          BRANCHES=$(echo ${result} | jq -c '.branches')
          FORCED_NONE=$(echo ${result} | jq -c '.forced_none')

          if [ ${BRANCH_COUNT} -eq 0 ] ; then
            echo "No cherry-pick branches"
            exit 0
          fi

          branches=$(echo $BRANCHES | jq -r '.[]')
          for b in $branches ; do
            gh cache delete -R ${REPO} ${BUILD_CACHE_KEY_PREFIX}-$b || :
          done

          gh pr edit --repo ${REPO} \
            --add-label ${TESTING_IN_PROGRESS} \
            ${PR_NUMBER} || :

      - name: CheckCherryPicks
        env:
          BRANCHES: ${{ steps.setup.outputs.branches }}
        run: |
          ${SCRIPT_DIR}/cherryPick.sh \
            --repo=${REPO} \
            --repo-dir=${REPO_DIR} \
            --pr-number=${PR_NUMBER} \
            --output-dir=${LOG_DIR} \
            --branches="${BRANCHES}"

      - name: Save Output
        id: save-output
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Setup
          if-no-files-found: ignore
          path: ${{ env.LOG_DIR }}

  Check:
    needs: [Setup]
    if: ${{ needs.Setup.outputs.branch_count > 0 && ( success() ) }}
    permissions:
      actions: read
      checks: read
      contents: read
      issues: read
      pull-requests: read
      statuses: read
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJSON(needs.Setup.outputs.branches) }}
    uses: ./.github/workflows/TestsuiteRunUnitTests.yml
    with:
      pr_number:         ${{ github.event.number }}
      base_branch:       ${{ matrix.branch }}
      unittest_command:  ${{ vars.UNITTEST_COMMAND }}

  PostWorkflow:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [Setup,Check]
    env:
      RESULT_SETUP:   ${{ needs.Setup.result }}
      RESULT_CHECK:   ${{ needs.Check.result }}
      BRANCHES: ${{ needs.Setup.outputs.branches }}
    steps:
        # ACTIONS_PATH, SCRIPT_DIR, NORMALIZED_BRANCH env vars
      - name: GetActionsRepo
        uses: asterisk/asterisk-ci-actions/GetActionsRepo@main

      - name: Check status
        run: |
          label=""
          RESULT=$RESULT_CHECK
          branches=$(echo $BRANCHES | jq -r '.[]')
          echo "Branches: ${branches}"
          echo "Setup status: $RESULT_SETUP Check status: $RESULT_CHECK"
          case $RESULT_CHECK in
            success)
              label=$TESTS_PASSED
              for b in $branches ; do
                gh cache delete -R ${REPO} ${BUILD_CACHE_KEY_PREFIX}-$b || :
              done
              ;;
            failure)
              label=$TESTS_FAILED
              ;;
            cancelled)
              for b in $branches ; do
                gh cache delete -R ${REPO} ${BUILD_CACHE_KEY_PREFIX}-$b || :
              done
              ;;
            skipped)
              if [ "$RESULT_SETUP" == "failure" ] ; then
                  RESULT=failure
                  label=$TESTS_FAILED
              fi
              ;;
            *)
              ;;
          esac

          echo "RESULT: '${RESULT}'  Setting label: '$label'"
          gh pr edit --repo ${REPO} \
            --remove-label ${TESTING_IN_PROGRESS} \
            ${label:+--add-label $label} \
              $PR_NUMBER || :

          if [[ $RESULT =~ (success|failure) ]] ; then
            ${SCRIPT_DIR}/createJobSummary.sh \
              --result=${RESULT} \
              --repo=${REPO} \
              --workflow-name="${WORKFLOW_NAME}" \
              --pr-number=${PR_NUMBER} \
              --workflow-run=${WORKFLOW_RUN_ID} \
              --tmp-dir=./run-${WORKFLOW_RUN_ID} \
              --job-summary-output=job_summary.txt \
              --write-step-summary \
              --add-pr-comment \
              --verbose || :
          fi
          exit 0
