name: TestWorkflow
run-name: "TestWorkflow"
on:
  workflow_dispatch:
    inputs:
      branches:
        required: false
        type: string
        description: "Array of branches to run: ['21','master'].  Defaults to NIGHTLYTEST_BRANCHES"
      group_list:
        required: false
        type: string
        description: "Array of test groups to run: ['ari1','channels'].  Defaults to NIGHTLYTEST_LIST"

jobs:

  NightlyTestMatrix:
    uses: ./.github/workflows/AsteriskUnitGateTest.yml
    with:
      test_type:         nightly
      asterisk_repo:     ${{github.repository}}
      pr_number:         0
      base_branch:       master
      is_cherry_pick:    false
      build_options:     ${{vars.BUILD_OPTIONS}}
      unittest_command:  ${{vars.UNITTEST_COMMAND}}
      testsuite_test_type: Nightly
      testsuite_repo:    ${{vars.TESTSUITE_REPO}}
      gatetest_list:     ${{inputs.group_list}}
      gatetest_commands: ${{vars.GATETEST_COMMANDS}}
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
