name: TestWorkflow
run-name: "TestWorkflow"
on:
  workflow_dispatch:
    inputs:
      email_to:
        description: "Email address"
        required:    true
        type:        string

permissions:
  actions: write
  checks: read
  contents: write
  issues: read
  pull-requests: write
  statuses: read

jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: |
          cat <<-EOF > /tmp/email.txt
          This is a test of the send email action.
          EOF

      - name: Send Release Announcements
        uses: dawidd6/action-send-mail@v16
        with:
          server_address: email-smtp.us-east-1.amazonaws.com
          server_port: 587
          secure: false
          username: ${{secrets.ASTERISKTEAM_SES_KEY_ID}}
          password: ${{secrets.ASTERISKTEAM_SES_KEY_SECRET}}
          subject: 'Test Email'
          to: ${{ inputs.email_to }}
          from: Asterisk Development Team <asteriskteam@sangoma.com>
          body: "file:///tmp/email.txt"
          reply_to: no-reply+asteriskteam@sangoma.com
          ignore_cert: true
          convert_markdown: false
