name: TestWorkflow
run-name: "TestWorkflow"
on:
  workflow_dispatch:
    inputs:
      branches:
        description: "JSON array of branches: ['18','20'] (no spaces) or leave blank for all current branches."
        required:    false
        type:        string

env:
  FROM_WF: "from workflow"

jobs:
  Job1:
    runs-on: ubuntu-latest
    env:
      FROM_JOB: "from job"
    defaults:
      run:
        shell: bash
    steps:
      - name: Send email
        uses: devellany/send-mail@v1.0.2
        with:
          host: smtp-mail.outlook.com
            # Optional port (defaults to 465)
          port: 587
          account: ${{ secrets.ASTERISKTEAMSA_USERNAME }}
          password: ${{ secrets.ASTERISKTEAMSA_PASSWORD }}
          sender: Asterisk Team
          from: asteriskteamsa@sangoma.com
          to: gjoseph@sangoma.com
          subject: mail title.
          body: your messages.
          # Optional content type (defaults to text/plain)
          contentType: text/plain
          # Optional attachment files (JSON type. require property 'path')
          attachments: '[{"path":"README.md"}]'

