name: TestWorkflow
run-name: "TestWorkflow"
on:
  workflow_dispatch:

env:
  ACTIONS_OWNER:     asterisk
  ACTIONS_REPO:      asterisk-ci-actions
  ACTIONS_BRANCH:    main-test-native
  SCRIPT_DIR:        ${{ github.workspace }}/asterisk-ci-actions/scripts

jobs:
  Setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Setup
        run: |
          # Setup
          pwd
          wget -qO asterisk-ci-actions.tar.gz \
            https://github.com/${ACTIONS_OWNER}/${ACTIONS_REPO}/archive/refs/heads/${ACTIONS_BRANCH}.tar.gz
          tar -xf asterisk-ci-actions.tar.gz --transform="s/^${ACTIONS_REPO}-${ACTIONS_BRANCH}/asterisk-ci-actions/g"
          # jq -r '. | from_entries' ${ACTIONS_REPO}/.github/control/asterisk-gh-test.json
          sed -i -r -e "s/^vars_/export vars_/g" ${ACTIONS_REPO}/.github/control/asterisk-gh-test.env
          source ${ACTIONS_REPO}/.github/control/asterisk-gh-test.env
          for VV in ${!vars_@} ; do
            echo "$VV=${!VV}" >> "${GITHUB_ENV}"
          done

      - name: Printenv
        run: |
          printenv

#      - name: DumpEnvironment
#        uses: asterisk/asterisk-ci-actions/DumpEnvironmentAction@main
