name: TestCalledWorkflow
run-name: "TestCalledWorkflow"
on:
  workflow_call:
    inputs:
      actions_ref:
        description: 'JSON object reference to the actions: { "owner": "asterisk", "repo": "asterisk-ci-actions", "branch": "main" }'
        type: string
        required: false
        default: '{ "owner": "asterisk", "repo": "asterisk-ci-actions", "branch": "main" }'
      jobname:
        type: string
        required: true
    secrets:
      TOKEN:
        required: true

env:
  ACTIONS_OWNER:     asterisk
  ACTIONS_REPO:      asterisk-ci-actions
  ACTIONS_BRANCH:    main
  SCRIPT_DIR:        ${{ github.workspace }}/asterisk-ci-actions/scripts
  GH_TOKEN:          ${{secrets.TOKEN}}
  RUN_ID:            ${{ github.run_id }}

jobs:
  Job1:
    name: ${{inputs.jobname}}-Job1
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: DumpEnvironment
        uses: asterisk/asterisk-ci-actions/DumpEnvironmentAction@main
        with:
          save_output: true
          artifact_id: DumpEnvironment-${{inputs.jobname}}-Job1

      - name: test
        run: |
          mkdir logs
          step_summary=""
          step_summary+="FAILURE: rest_api/recording/duration\nFAILURE: rest_api/recording/nominal"
          echo -e "$step_summary" >> logs/job_summary.txt
          exit 1
      - name: Save Output
        id: save-output
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{inputs.jobname}}-Job1
          path: |
            logs

  Job2:
    runs-on: ubuntu-latest
    name: ${{inputs.jobname}}-Job2
    defaults:
      run:
        shell: bash
    steps:
      - name: test
        run: |
          mkdir logs
          step_summary=""
          step_summary+="FAILURE: rest_api/recording/XXXXX\nFAILURE: rest_api/recording/YYYYYYY"
          echo -e "$step_summary" >> logs/job_summary.txt
          echo "::group::outer group"
          echo "outer 1"
          echo "outer 2"
          echo "::group::inner group"
          echo "inner 1"
          echo "inner 2"
          echo "::endgroup::"
          echo "outer 3"
          echo "outer 4"
          echo "::endgroup::"
          
          exit 0
      - name: Save Output
        id: save-output
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{inputs.jobname}}-Job2
          path: |
            logs
      - name: DumpEnvironment
        uses: asterisk/asterisk-ci-actions/DumpEnvironmentAction@main

