name: TestWorkflow
run-name: "TestWorkflow"
on:
  workflow_dispatch:
    inputs:
      branches:
        description: "JSON array of branches: ['18','20'] (no spaces) or leave blank for all current branches."
        required:    false
        type:        string

env:
  FROM_WF: "from workflow"

jobs:
  Job1:
    runs-on: ubuntu-latest
    env:
      FROM_JOB: "from job"
    defaults:
      run:
        shell: bash
    steps:
        # ACTIONS_PATH, SCRIPT_DIR, NORMALIZED_BRANCH env vars
      - name: GetActionsRepo
        uses: asterisk/asterisk-ci-actions/GetActionsRepo@main-pr-target

      - name: DumpEnvironment
        uses: asterisk/asterisk-ci-actions/DumpEnvironmentAction@main

      - name: printenv
        env:
          FROM_STEP: "from step"
          SSS: ${{ secrets.SOME_SUPER_SECRET }}
        run: |
          FROM_STEP_SHELL="from step shell"
          export FROM_STEP_SHELL_EXPORTED="from step shell exported"
          ${SCRIPT_DIR}/printEnv.sh
