name: TestWorkflow
run-name: "TestWorkflow"
on:
  workflow_dispatch:
    inputs:
      test_type:
        type: string
        default: "Nightly"
      base_branch:
        type: string
        default: master
      user_group:
        type: string
        default: asteriskci:users
      testsuite_repo:
        description: 'Testsuite Repo (default: asterisk/testsuite)'
        type: string
        default: asterisk/testsuite
      testsuite_test_pr:
        type: string
      gatetest_group:
        description: 'Gate Group'
        type: string
        default: "somegroup"
      gatetest_commands:
        description: 'Gate Commands'
        type: string
        default: '[]'
      build_cache_dir:
        type: string
        default: build-cache
      build_cache_key:
        type: string
        default: "akey"

env:
  COUNTER: 42

jobs:
  TestCalledWorkflow:
    uses: ./.github/workflows/TestCalledWorkflow.yml
    with:
      test_type:         ${{ inputs.test_type }}
      base_branch:       ${{ inputs.base_branch }}
      build_cache_dir:   ${{ inputs.build_cache_dir }}
      build_cache_key:   ${{ github.workflow }}-${{ inputs.pr_number }}-${{ inputs.base_branch }}
    secrets: inherit
