name: TestWorkflow
run-name: "TestWorkflow"
on:
  workflow_dispatch:
    inputs:
      counter:
        type: number
        default: 0

env:
  COUNTER: 42

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
#      - name: DumpEnvironment
#        uses: asterisk/asterisk-ci-actions/DumpEnvironmentAction@main
#        with:
#          action-inputs: ${{ toJSON(inputs) }}
#
      - name: CreateIssue
        env:
          GH_TOKEN: ${{secrets.ASTERISKTEAM_PAT}}
        run: |
          gh issue create -R freepbx/github-integration-test \
            --title 'Asterisk Version blah Has Been Released' \
            --body 'Asterisk Version blah Has Been Released' 


