name: TestWorkflow
run-name: "TestWorkflow"
on:
  workflow_dispatch:

jobs:
  Build:
    uses: ./.github/workflows/AsteriskBuildAndCache.yml
    with:
      test_type:         nightly
      asterisk_repo:     asterisk/asterisk
      pr_number:         931
      base_branch:       master
      is_cherry_pick:    false
      build_cache_key:   ${{ github.workflow }}-931-master
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ShowCache:
    needs: [ Build ]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Setup Runner
        uses: asterisk/asterisk-ci-actions/SetupUbuntuRunner@main-test-native

      - name: Restore Asterisk Cache
        uses: asterisk/asterisk-ci-actions/RestoreAsteriskFromCache@main
        with:
          repo_dir:        asterisk
          build_cache_dir: build-cache
          build_cache_key: ${{ github.workflow }}-931-master
          user_group:      asteriskci:users
      - name: showcache
        run: |
          # Show Cache
          find build-cache