name: TestCalledWorkflow
run-name: "TestCalledWorkflow"
on:
  workflow_call:
    inputs:
      gatetest_group:
        type: string
        required: true
      gatetest_commands:
        type: string
        required: true

env:
  GATETEST_GROUP:     ${{ inputs.gatetest_group }}
  GATETEST_COMMAND:   ${{ toJSON(fromJSON(inputs.gatetest_commands)[inputs.gatetest_group]) }}

jobs:
  Job2Called:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
      steps:
        - name: Test GET
          run: |
            echo "GROUP: ${{inputs.gatetest_group}}"
            echo "COMMANDS: ${{inputs.gatetest_commands}}"
            echo "${{ toJSON(fromJSON(inputs.gatetest_commands)[inputs.gatetest_group]) }}"
            echo "--------------------------"
            echo "GROUP: ${GATETEST_GROUP}"
            echo "CMD: ${GATETEST_COMMAND}"


