name: RunUnitTests
on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: string
      base_branch:
        required: true
        type: string
      unittest_command:
        type: string
        required: true

env:
  REPO:             ${{ github.repository }}
  REPO_DIR:         ${{ github.event.repository.name }}
  REPO_ORG:         ${{ github.event.repository.owner.login }}
  GH_TOKEN:         ${{ secrets.GITHUB_TOKEN }}
  BASE_BRANCH:      ${{ inputs.base_branch }}
  PR_NUMBER:        ${{ inputs.pr_number }}
  UNITTEST_COMMAND: ${{ inputs.unittest_command }}

jobs:
  RunUnitTests:
    name: ${{ inputs.base_branch }}-unit
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
        # ACTIONS_PATH, SCRIPT_DIR, NORMALIZED_BRANCH env vars
      - name: GetActionsRepo
        uses: asterisk/asterisk-ci-actions/GetActionsRepo@main

      - name: "Setup testsuite"
        run: |
          # Setup testsuite
          ${SCRIPT_DIR}/checkoutRepo.sh --repo="${REPO}" \
            --repo-dir="${REPO_DIR}" --branch="${BASE_BRANCH}" \
            --pr-number=${PR_NUMBER} --is-cherry-pick

      - name: Run Unit Tests
        run: |
          # Run Unit Tests
          cd ${REPO_DIR}
          echo "Installing libpcap-dev for yappcap"
          sudo apt-get install -y libpcap-dev
          echo "Setting up virtualenv"
          ./setupVenv.sh
          echo "Running self tests"
          ./runInVenv.sh ./self_test && echo "Self tests passed" || echo "Self tests failed"
