name: UpdateControlData
run-name: "UpdateControlData"
on:
  workflow_dispatch:
    inputs:
      repo:
        description: |
          The repo in the asterisk org to copy the control data from:
        required: true
        type: string
  workflow_call:
    inputs:
      repo:
        description: |
          The repo in the asterisk org to copy the control data from:
        required: true
        type: string

jobs:
  UpdateControlData:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          set-safe-directory: true
      - name: checkdata
        env:
          CONTROLDATA_BASE: "${{ vars.CONTROLDATA_BASE }}"
          CONTROLDATA_JSON: "${{ inputs.repo }}.json"
          CONTROLDATA_ENV: "${{ inputs.repo }}.env"
          REPO: ${{ inputs.repo }}
          GH_TOKEN:   ${{ secrets.ASTERISKTEAM_PAT }}
        run: |
          echo "Current Directory: $PWD"
          csum1=""
          if [ -f ./.github/control/${CONTROLDATA_JSON} ] ; then
            csum1=$(md5sum ./.github/control/${CONTROLDATA_JSON})
            echo "CSUM1: $csum1"
          fi
          echo "Retriving variables from repo $REPO in JSON format"
          gh api --jq .variables --paginate -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/asterisk/${REPO}/actions/variables | jq -s add > /tmp/${CONTROLDATA_JSON}
          csum2=$(md5sum /tmp/${CONTROLDATA_JSON})
          echo "Retriving variables from repo $REPO in ENV format"
          gh api --paginate /repos/asterisk/${REPO}/actions/variables \
            --jq '.variables[] | "vars_" + .name + "=$" + (.value | @sh)' > /tmp/${CONTROLDATA_ENV}
          echo "CSUM2: $csum2"
          if [ "${csum1%% *}" == "${csum2%% *}" ] ; then
            echo "No change for $REPO"
            exit 0
          fi
          echo "Need to commit new version"
          git config --global user.email "asteriskteam@digium.com"
          git config --global user.name "Asterisk Development Team"
          git pull
          cp /tmp/${CONTROLDATA_JSON} ./.github/control/${CONTROLDATA_JSON}
          cp /tmp/${CONTROLDATA_ENV} ./.github/control/${CONTROLDATA_ENV}
          git add ./.github/control/${CONTROLDATA_JSON} ./.github/control/${CONTROLDATA_ENV}
          git commit -a -m "Update control data for repo ${REPO}"
          git push
          exit 0
